version: '3.3'

services:
  db:
    image: postgres:13.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - .env.db
  web:
    build: .
    command: python /application/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/application
    ports:
      - "8000:8000"
    env_file:
      - .env.db
    depends_on:
      - db

volumes:
  postgres_data:
