version: '3.3'

services:
  db:
    image: postgres:13.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - .env.db
  web:
    image: 138941284341.dkr.ecr.eu-central-1.amazonaws.com/django-backend:latest
    command: python /application/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/application
      - static_volume:/usr/share/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    ports:
      - "8000:8000"
    env_file:
      - .env.db
    depends_on:
      - db
  nginx:
    image: nginx:latest
    command: rm /etc/nginx/conf.d/default.conf
    volumes:
      - ./templates/:/usr/share/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  media_volume:
  static_volume:
